# Generated by Django 5.1.2 on 2025-07-13 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250630_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(blank=True, choices=[('fit', 'Fit'), ('weight_gain', 'Weight_Gain'), ('weight_loss', 'Weight_Loss'), ('muscle_building', 'Muscle_Building'), ('phisical_therapy', 'Phisical_Therapy')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainee')),
            ],
        ),
        migrations.AddField(
            model_name='trainee',
            name='courses',
            field=models.ManyToManyField(through='users.Enrollment', to='users.course'),
        ),
    ]
